WITH cte_tiktok AS
         (SELECT 3                                                                  AS platform_id,
                 'TIKTOK'                                                           AS platform_name,
                 JSONExtractInt(_airbyte_data, 'likes')                             AS likes,
                 JSONExtractInt(_airbyte_data, 'new_followers')                     AS new_followers,
                 JSONExtractInt(_airbyte_data, 'reach')                             AS reach,
                 JSONExtractInt(_airbyte_data, 'website_clicks')                    AS website_clicks,
                 JSONExtractInt(_airbyte_data, 'lead_submissions')                  AS lead_submissions,
                 toDateTime(JSONExtractInt(_airbyte_data, 'create_time'))           AS create_time,
                 JSONExtractInt(_airbyte_data, 'app_download_clicks')               AS app_download_clicks,
                 JSONExtractInt(_airbyte_data, 'phone_number_clicks')               AS phone_number_clicks,
                 JSONExtractString(_airbyte_data, 'caption')                        AS caption,
                 extractAll(caption, '#(?:[\\wÀ-ỹđĐ_]+)')                           AS tags,
                 JSONExtractInt(_airbyte_data, 'shares')                            AS shares,
                 JSONExtractInt(_airbyte_data, 'comments')                          AS comments,
                 JSONExtractString(_airbyte_data, 'thumbnail_url')                  AS thumbnail_url,
                 JSONExtractFloat(_airbyte_data, 'video_duration')                  AS video_duration,
                 JSONExtractInt(_airbyte_data, 'favorites')                         AS favorites,
                 JSONExtractInt(_airbyte_data, 'video_views')                       AS video_views,
                 JSONExtractFloat(_airbyte_data, 'full_video_watched_rate')         AS full_video_watched_rate,
                 JSONExtractInt(_airbyte_data, 'profile_views')                     AS profile_views,
                 JSONExtractString(_airbyte_data, 'embed_url')                      AS embed_url,
                 JSONExtractFloat(_airbyte_data, 'average_time_watched')            AS average_time_watched,
                 JSONExtractString(_airbyte_data, 'item_id')                        AS content_id,
                 JSONExtractFloat(_airbyte_data, 'total_time_watched')              AS total_time_watched,
                 JSONExtractString(_airbyte_data, 'share_url')                      AS share_url,
                 JSONExtractRaw(JSONExtractRaw(_airbyte_data, 'user'), 'user_info') AS user_info,
                 JSONExtractString(user_info, 'profile_deep_link')                  AS profile_deep_link,
                 JSONExtractInt(user_info, 'following_count')                       AS following_count,
                 JSONExtractBool(user_info, 'is_verified')                          AS is_verified,
                 JSONExtractString(user_info, 'display_name')                       AS display_name,
                 JSONExtractString(user_info, 'username')                           AS username,
                 JSONExtractBool(user_info, 'is_business_account')                  AS is_business_account,
                 JSONExtractString(user_info, 'profile_image')                      AS profile_image,
                 JSONExtractInt(user_info, 'total_likes')                           AS total_likes,
                 JSONExtractString(user_info, 'bio_description')                    AS bio_description,
                 JSONExtractString(_airbyte_data, 'business_id')                    AS business_id,
                 _airbyte_data                                                      AS _raw,
                 _airbyte_extracted_at                                              AS _crawl_at
          FROM {{ source('tiktok_raw_data', 'raw_tiktok_video_metadata') }})
SELECT ct.platform_id                                                                          AS platform_id,
       ct.platform_name                                                                        AS platform_name,
       concat(ct.platform_id, '__', ct.business_id)                                            AS account_id,
       ct.business_id                                                                          AS platform_account_id,
       ct.username                                                                             AS user_name,
       ct.username                                                                             AS account_name,
       ct.tags                                                                                 AS tags,
       concat(ct.platform_id, '__', ct.business_id)                                            AS page_id,
       ct.business_id                                                                          AS platform_page_id,
       ct.display_name                                                                         AS page_name,
       concat(ct.platform_id, '__', ct.content_id)                                             AS content_id,
       ct.content_id                                                                           AS platform_content_id,
       multiIf(ct.video_duration = 0, 'CAROUSEL_ALBUM', ct.video_duration != 0, 'VIDEO', NULL) AS content_type,
       ct.create_time                                                                          AS created_time,
       ct.caption                                                                              AS caption,
       ct.profile_image                                                                        AS page_thumbnail_url,
       ct.thumbnail_url                                                                        AS thumbnail_url,
       ct.embed_url                                                                            AS permalink,
       concat(ct.platform_id, '__', ct.business_id)                                            AS created_user,
       ct._raw                                                                                 AS _raw,
       ct._crawl_at                                                                            AS _crawl_at
FROM cte_tiktok AS ct



{% if is_incremental() %}
    where _crawl_at > (select max(_crawl_at) from {{ this }})
{% endif %}